export const CARTINCREASE = "CARTINCREASE";
export const ISLOGIN = "ISLOGIN";
export const ADDTOCART = "ADDTOCART";
export const DELETEFROMCART = "DELETEFROMCART";
export const ISLOGINASSELLER = "ISLOGINASSELLER";
export const ISLOGINASBIDDER = "ISLOGINASBIDDER";
export const ISLOGINASADMIN = "ISLOGINASADMIN";
export const UPDATE_USER_NAME = "UPDATE_USER_NAME";
