export const product = [
  {
    id: 1,
    catname: "gedget",
    name: "iphone",
    price: 100000,
    img: "images/iphone.jpg",
    minprice: 100000,
  },
  {
    id: 2,
    catname: "gedget",
    name: "TAB",
    price: 100000,
    img: "images/tab.jpg",
    minprice: 100000,
  },
  {
    id: 3,
    catname: "gedget",
    name: "Samsung",
    price: 143562,
    img: "images/samsung.jpeg",
    minprice: 100000,
  },
  {
    id: 4,
    catname: "gedget",
    name: "LG",
    price: 165364,
    img: "images/lg.jpeg",
    minprice: 100000,
  },
  {
    id: 5,
    catname: "gedget",
    name: "Apple",
    price: 165363,
    img: "images/apple.jpeg",
    minprice: 100000,
  },
  {
    id: 6,
    catname: "gedget",
    name: "Huawei",
    price: 298222,
    img: "images/Huawei.jpeg",
    minprice: 100000,
  },
  {
    id: 7,
    catname: "gedget",
    name: "Oppo",
    price: 100033,
    img: "images/oppo.jpeg",
    minprice: 100000,
  },
  {
    id: 8,
    catname: "gedget",
    name: "Vivo",
    price: 16000,
    img: "images/vivo.jpeg",
    minprice: 100000,
  },
  {
    id: 9,
    catname: "gedget",
    name: "Xiaomi",
    price: 8000,
    img: "images/xiome.jpeg",
    minprice: 100000,
  },
  {
    id: 10,
    catname: "food",
    name: "Pizza",
    price: 500,
    img: "images/pizza.jpeg",
    minprice: 100000,
  },
  {
    id: 11,
    catname: "food",
    name: "Burgar",
    price: 800,
    img: "images/burger.jpeg",
    minprice: 100000,
  },
  {
    id: 12,
    catname: "food",
    name: "Chicken",
    price: 543,
    img: "images/chicken.jpeg",
    minprice: 100000,
  },
];
export const food = [
  {
    id: 1,
    catname: "food",
    name: "Pizza",
    price: 500,
    img: "images/pizza.jpeg",
    minprice: 100000,
  },
  {
    id: 2,
    catname: "food",
    name: "Burgar",
    price: 800,
    img: "images/burger.jpeg",
    minprice: 100000,
  },
  {
    id: 3,
    catname: "food",
    name: "Chicken",
    price: 543,
    img: "images/chicken.jpeg",
    minprice: 100000,
  },
];

